export default {
  REQUEST_ISSUES: 'REQUEST_ISSUES',
  RECEIVE_ISSUES: 'RECEIVE_ISSUES',

  REQUEST_REPOS: 'REQUEST_REPOS',
  RECEIVE_REPOS: 'RECEIVE_REPOS',

  REQUEST_TIMELINE: 'REQUEST_TIMELINE',
  RECEIVE_TIMELINE: 'RECEIVE_TIMELINE',

  REQUEST_NOTIFICATIONS: 'REQUEST_NOTIFICATIONS',
  RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',

  REQUEST_TRENDING: 'REQUEST_TRENDING',
  RECEIVE_TRENDING: 'RECEIVE_TRENDING'
}
