# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'githubnative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for githubnative

  target 'githubnative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'githubnativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
